# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(685, 704)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.aRadio = QtWidgets.QRadioButton(self.centralwidget)
        self.aRadio.setChecked(True)
        self.aRadio.setObjectName("aRadio")
        self.horizontalLayout.addWidget(self.aRadio)
        self.oRadio = QtWidgets.QRadioButton(self.centralwidget)
        self.oRadio.setObjectName("oRadio")
        self.horizontalLayout.addWidget(self.oRadio)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.nomeEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.nomeEdit.setObjectName("nomeEdit")
        self.horizontalLayout_2.addWidget(self.nomeEdit)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.seiEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.seiEdit.setObjectName("seiEdit")
        self.horizontalLayout_3.addWidget(self.seiEdit)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.comissaoEdit1 = QtWidgets.QLineEdit(self.groupBox)
        self.comissaoEdit1.setObjectName("comissaoEdit1")
        self.verticalLayout.addWidget(self.comissaoEdit1)
        self.comissaoEdit2 = QtWidgets.QLineEdit(self.groupBox)
        self.comissaoEdit2.setObjectName("comissaoEdit2")
        self.verticalLayout.addWidget(self.comissaoEdit2)
        self.comissaoEdit3 = QtWidgets.QLineEdit(self.groupBox)
        self.comissaoEdit3.setObjectName("comissaoEdit3")
        self.verticalLayout.addWidget(self.comissaoEdit3)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.deEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.deEdit.setObjectName("deEdit")
        self.horizontalLayout_5.addWidget(self.deEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.paraEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.paraEdit.setObjectName("paraEdit")
        self.horizontalLayout_4.addWidget(self.paraEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_8.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        self.dateEdit = QtWidgets.QDateEdit(self.groupBox_3)
        self.dateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2020, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateEdit.setObjectName("dateEdit")
        self.horizontalLayout_6.addWidget(self.dateEdit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_7.addWidget(self.label_6)
        self.dateEdit_2 = QtWidgets.QDateEdit(self.groupBox_3)
        self.dateEdit_2.setDateTime(QtCore.QDateTime(QtCore.QDate(2020, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.horizontalLayout_7.addWidget(self.dateEdit_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8.addWidget(self.groupBox_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.atividadesDeEnsinoLabel = QtWidgets.QLabel(self.groupBox_4)
        self.atividadesDeEnsinoLabel.setObjectName("atividadesDeEnsinoLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.atividadesDeEnsinoLabel)
        self.ensinoSpin = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.ensinoSpin.setMaximum(999.99)
        self.ensinoSpin.setObjectName("ensinoSpin")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ensinoSpin)
        self.pesquisaEOuExtensOLabel = QtWidgets.QLabel(self.groupBox_4)
        self.pesquisaEOuExtensOLabel.setObjectName("pesquisaEOuExtensOLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.pesquisaEOuExtensOLabel)
        self.pesquisaSpin = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.pesquisaSpin.setMaximum(999.99)
        self.pesquisaSpin.setObjectName("pesquisaSpin")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.pesquisaSpin)
        self.administraORepresentaOEOutrasLabel = QtWidgets.QLabel(self.groupBox_4)
        self.administraORepresentaOEOutrasLabel.setObjectName("administraORepresentaOEOutrasLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.administraORepresentaOEOutrasLabel)
        self.admSpin = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.admSpin.setMaximum(999.99)
        self.admSpin.setObjectName("admSpin")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.admSpin)
        self.didTicoLabel = QtWidgets.QLabel(self.groupBox_4)
        self.didTicoLabel.setObjectName("didTicoLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.didTicoLabel)
        self.didaticoSpin = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.didaticoSpin.setMaximum(999.99)
        self.didaticoSpin.setObjectName("didaticoSpin")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.didaticoSpin)
        self.somaLabel = QtWidgets.QLabel(self.groupBox_4)
        self.somaLabel.setObjectName("somaLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.somaLabel)
        self.somaSpin = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.somaSpin.setMaximum(999.99)
        self.somaSpin.setObjectName("somaSpin")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.somaSpin)
        self.verticalLayout_5.addLayout(self.formLayout)
        self.horizontalLayout_9.addWidget(self.groupBox_4)
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.atividadesDeEnsinoLabel_2 = QtWidgets.QLabel(self.groupBox_5)
        self.atividadesDeEnsinoLabel_2.setObjectName("atividadesDeEnsinoLabel_2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.atividadesDeEnsinoLabel_2)
        self.ensinoSpin_2 = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.ensinoSpin_2.setMaximum(999.99)
        self.ensinoSpin_2.setObjectName("ensinoSpin_2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ensinoSpin_2)
        self.pesquisaEOuExtensOLabel_2 = QtWidgets.QLabel(self.groupBox_5)
        self.pesquisaEOuExtensOLabel_2.setObjectName("pesquisaEOuExtensOLabel_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.pesquisaEOuExtensOLabel_2)
        self.pesquisaSpin_2 = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.pesquisaSpin_2.setMaximum(999.99)
        self.pesquisaSpin_2.setObjectName("pesquisaSpin_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.pesquisaSpin_2)
        self.administraORepresentaOEOutrasLabel_2 = QtWidgets.QLabel(self.groupBox_5)
        self.administraORepresentaOEOutrasLabel_2.setObjectName("administraORepresentaOEOutrasLabel_2")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.administraORepresentaOEOutrasLabel_2)
        self.admSpin_2 = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.admSpin_2.setMaximum(999.99)
        self.admSpin_2.setObjectName("admSpin_2")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.admSpin_2)
        self.didTicoLabel_2 = QtWidgets.QLabel(self.groupBox_5)
        self.didTicoLabel_2.setObjectName("didTicoLabel_2")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.didTicoLabel_2)
        self.didaticoSpin_2 = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.didaticoSpin_2.setMaximum(999.99)
        self.didaticoSpin_2.setObjectName("didaticoSpin_2")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.didaticoSpin_2)
        self.somaLabel_2 = QtWidgets.QLabel(self.groupBox_5)
        self.somaLabel_2.setObjectName("somaLabel_2")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.somaLabel_2)
        self.somaSpin_2 = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.somaSpin_2.setMaximum(999.99)
        self.somaSpin_2.setObjectName("somaSpin_2")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.somaSpin_2)
        self.verticalLayout_6.addLayout(self.formLayout_2)
        self.horizontalLayout_9.addWidget(self.groupBox_5)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_4.addWidget(self.textBrowser)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Janela"))
        self.aRadio.setText(_translate("MainWindow", "Prof.ª"))
        self.oRadio.setText(_translate("MainWindow", "Prof.º"))
        self.label.setText(_translate("MainWindow", "Nome:"))
        self.label_2.setText(_translate("MainWindow", "SEI:"))
        self.groupBox.setTitle(_translate("MainWindow", "Comissão de avaliação"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Progressão"))
        self.label_3.setText(_translate("MainWindow", "De:"))
        self.label_4.setText(_translate("MainWindow", "Para:"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Interstício:"))
        self.label_5.setText(_translate("MainWindow", "De:"))
        self.label_6.setText(_translate("MainWindow", "Para:"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Pontuação:"))
        self.atividadesDeEnsinoLabel.setText(_translate("MainWindow", "Ensino"))
        self.pesquisaEOuExtensOLabel.setText(_translate("MainWindow", "Pesquisa e/ou Extensão"))
        self.administraORepresentaOEOutrasLabel.setText(_translate("MainWindow", "<html><head/><body>Administração, <br/>Representação e Outras</body></html>"))
        self.didTicoLabel.setText(_translate("MainWindow", "Didático"))
        self.somaLabel.setText(_translate("MainWindow", "Soma"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Pontos excedentes"))
        self.atividadesDeEnsinoLabel_2.setText(_translate("MainWindow", "Ensino"))
        self.pesquisaEOuExtensOLabel_2.setText(_translate("MainWindow", "Pesquisa e/ou Extensão"))
        self.administraORepresentaOEOutrasLabel_2.setText(_translate("MainWindow", "<html><head/><body>Administração, <br/>Representação e Outras</body></html>"))
        self.didTicoLabel_2.setText(_translate("MainWindow", "Didático"))
        self.somaLabel_2.setText(_translate("MainWindow", "Soma"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Verdana,Geneva,sans-serif\'; font-weight:600; color:#2c363a; background-color:#ffffff;\">Homologação do parecer de progressão funcional da Profa. Flavia Cristiane Farina, aprovado </span><span style=\" font-family:\'Verdana,Geneva,sans-serif\'; font-weight:600; font-style:italic; color:#2c363a; background-color:#ffffff;\">adreferendum</span><span style=\" font-family:\'Verdana,Geneva,sans-serif\'; font-weight:600; color:#2c363a; background-color:#ffffff;\">: </span><span style=\" font-family:\'Verdana,Geneva,sans-serif\'; color:#2c363a; background-color:#ffffff;\">(Processo SEI: 23078.504959/2020-73) A Comissão de avaliação, formada pelos professores Sergio Florêncio de Souza, Silvia Beatriz Alves Rolim e Carlos Augusto Sommer, emitiu parecer que considerou terem sido cumpridos os requisitos necessários para obtenção da progressão de Associado I para Associado II, no interstício de 10.02.2018 a 09.02.2020, através das seguintes pontuações: Atividades de Ensino: 58,0; Atividades de Pesquisa e/ou Extensão: 103,2; Atividades de Administração, Representação e Outras: 37,5; Desempenho Didático: 9,2; totalizando a soma de 207,9 pontos. Pontos excedentes para próxima avaliação, que não tenham sido utilizados para completar a pontuação mínima total: 26,0, referentes à Atividade de Ensino, e 78,2, relativos a Atividades de Pesquisa e/ou Extensão, totalizando a soma de 104,2. </span><span style=\" font-family:\'Verdana,Geneva,sans-serif\'; font-weight:600; color:#2c363a; background-color:#ffffff;\">Aprovado.</span></p></body></html>"))

